sonar.organization=itiss-hue
sonar.projectKey=ITISS-hue_my-sonar-project
sonar.projectName=devsecops
sonar.sources=.
sonar.exclusions=.github/workflows/**
sonar.coverage.exclusions=app.py, **/*
sonar.host.url=https://sonarcloud.io