sonar.organization=itiss-hue
sonar.projectKey=ITISS-hue_my-sonar-project
sonar.projectName=devsecops
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=.github/workflows/**
sonar.host.url=https://sonarcloud.io
sonar.sources=app.py
sonar.tests=tests
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**


