apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app-deployment
  labels:
    app: devsecops-app
spec:
  replicas: 2
  # Smooth rolling updates between 2 replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      # Fixes the hanging pod/timeout issue during pipeline execution (Forces old pod deletion in 5s)
      terminationGracePeriodSeconds: 5
      containers:
      - name: app-container
        image: avigyan2212/devsecops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "devsecops-production-fixed-secret-key-9988"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        # Resource quotas for cluster stability
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"